// file: CBRKbBasedFactoryException.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.CBR;


/** file: CBRKbBasedFactoryException.java
 * @author ontology bean generator
 * @version 2009/10/17, 19:00:45
 */
public class CBRKbBasedFactoryException extends Exception { 

  private static final long serialVersionUID = 1907932705116471396L;

  public CBRKbBasedFactoryException(String msg) {
    super(msg);
  }

  public CBRKbBasedFactoryException(String msg, Throwable thr) {
    super(msg, thr);
  }

  public CBRKbBasedFactoryException(Throwable thr) {
    super(thr);
  }

}

