// file: CommonKbBeanFactoryException.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.common;


/** file: CommonKbBeanFactoryException.java
 * @author ontology bean generator
 * @version 2009/09/30, 12:55:43
 */
public class CommonKbBeanFactoryException extends Exception { 

  private static final long serialVersionUID = 3978892154560758766L;

  public CommonKbBeanFactoryException(String msg) {
    super(msg);
  }

  public CommonKbBeanFactoryException(String msg, Throwable thr) {
    super(msg, thr);
  }

  public CommonKbBeanFactoryException(Throwable thr) {
    super(thr);
  }

}

