// file: CommonKbBasedFactoryException.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.common;


/** file: CommonKbBasedFactoryException.java
 * @author ontology bean generator
 * @version 2009/10/17, 11:59:53
 */
public class CommonKbBasedFactoryException extends Exception { 

  private static final long serialVersionUID = 8409500558378942440L;

  public CommonKbBasedFactoryException(String msg) {
    super(msg);
  }

  public CommonKbBasedFactoryException(String msg, Throwable thr) {
    super(msg, thr);
  }

  public CommonKbBasedFactoryException(Throwable thr) {
    super(thr);
  }

}

