// file: KbBasedBeanFactoryException.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.common;


/** file: KbBasedBeanFactoryException.java
 * @author ontology bean generator
 * @version 2009/09/15, 18:06:25
 */
public class KbBasedBeanFactoryException extends Exception { 

  private static final long serialVersionUID = -2693500281773954763L;

  public KbBasedBeanFactoryException(String msg) {
    super(msg);
  }

  public KbBasedBeanFactoryException(String msg, Throwable thr) {
    super(msg, thr);
  }

  public KbBasedBeanFactoryException(Throwable thr) {
    super(thr);
  }

}

