// file: CommonTerminologyOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.common;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: CommonTerminologyOntology.java
 * @author ontology bean generator
 * @version 2009/10/20, 13:36:12
 */
public class CommonTerminologyOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = 2105474187493131833L;

  //NAME
  public static final String ONTOLOGY_NAME = "CommonTerminology";
  // The singleton instance of this ontology
  private static Ontology theInstance = new CommonTerminologyOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String APPLIESTO_DESCRIPTIVEELEMENT="descriptiveElement";
    public static final String APPLIESTO_ATTRIBUTE="attribute";
    public static final String APPLIESTO="AppliesTo";
    public static final String DESCRIBEDBY_ATTRIBUTE="attribute";
    public static final String DESCRIBEDBY_SCORE="score";
    public static final String DESCRIBEDBY="DescribedBy";
    public static final String DESCRIBES_ATTRIBUTE="attribute";
    public static final String DESCRIBES_SCORE="score";
    public static final String DESCRIBES="Describes";
    public static final String ISDESCRIPTIVEELEMENT_DESCRIPTIVEELEMENT="descriptiveElement";
    public static final String ISDESCRIPTIVEELEMENT="IsDescriptiveElement";
    public static final String OWNS_DESCRIPTIVEELEMENT="descriptiveElement";
    public static final String OWNS_ATTRIBUTE="attribute";
    public static final String OWNS="Owns";
    public static final String DESCRIPTOR_STRUCTURE="structure";
    public static final String DESCRIPTOR_ATTRIBUTE="attribute";
    public static final String DESCRIPTOR_SCORE="score";
    public static final String DESCRIPTOR="Descriptor";
    public static final String QUANTITATIVECHARACTERDESCRIPTOR="QuantitativeCharacterDescriptor";
    public static final String MSCHARACTERDESCRIPTOR="MSCharacterDescriptor";
    public static final String SSCHARACTERDESCRIPTOR="SSCharacterDescriptor";
    public static final String QUALITATIVECHARACTERDESCRIPTOR="QualitativeCharacterDescriptor";
    public static final String QUALITATIVEHEURISTICDESCRIPTOR="QualitativeHeuristicDescriptor";
    public static final String HEURISTICDESCRIPTOR="HeuristicDescriptor";
    public static final String RVCHARACTERDESCRIPTOR="RVCharacterDescriptor";
    public static final String SVCHARACTERDESCRIPTOR="SVCharacterDescriptor";
    public static final String CHARACTERDESCRIPTOR="CharacterDescriptor";
    public static final String RANGEVALUE_LOWERBOUND="lowerBound";
    public static final String RANGEVALUE_UPPERBOUND="upperBound";
    public static final String RANGEVALUE="RangeValue";
    public static final String SINGLEVALUE_VALUE="value";
    public static final String SINGLEVALUE="SingleValue";
    public static final String DEFINEDTERM_TERM="term";
    public static final String DEFINEDTERM_DEFINITION="definition";
    public static final String DEFINEDTERM="DefinedTerm";
    public static final String STRUCTURE_OWNS="owns";
    public static final String STRUCTURE="Structure";
    public static final String ENVIRONMENTALCATEGORY_OWNS="owns";
    public static final String ENVIRONMENTALCATEGORY="EnvironmentalCategory";
    public static final String RVHEURISTICDESCRIPTOR="RVHeuristicDescriptor";
    public static final String DESCRIPTION_DESCRIPTORS="descriptors";
    public static final String DESCRIPTION="Description";
    public static final String SSHEURISTICDESCRIPTOR="SSHeuristicDescriptor";
    public static final String MSHEURISTICDESCRIPTOR="MSHeuristicDescriptor";
    public static final String QUANTITATIVEHEURISTICDESCRIPTOR="QuantitativeHeuristicDescriptor";
    public static final String SVHEURISTICDESCRIPTOR="SVHeuristicDescriptor";
    public static final String VALUE_DESCRIBES="describes";
    public static final String VALUE_MEASURINGUNIT="measuringUnit";
    public static final String VALUE="Value";
    public static final String ATTRIBUTE_DESCRIBEDBY="describedBy";
    public static final String ATTRIBUTE_APLIESTO="apliesTo";
    public static final String ATTRIBUTE="Attribute";
    public static final String STATE_DESCRIBES="describes";
    public static final String STATE="State";

  /**
   * Constructor
  */
  private CommonTerminologyOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema stateSchema = new ConceptSchema(STATE);
    add(stateSchema, Class.forName("ontology.common.State"));
    ConceptSchema attributeSchema = new ConceptSchema(ATTRIBUTE);
    add(attributeSchema, Class.forName("ontology.common.Attribute"));
    ConceptSchema valueSchema = new ConceptSchema(VALUE);
    add(valueSchema, Class.forName("ontology.common.Value"));
    ConceptSchema svHeuristicDescriptorSchema = new ConceptSchema(SVHEURISTICDESCRIPTOR);
    add(svHeuristicDescriptorSchema, Class.forName("ontology.common.SVHeuristicDescriptor"));
    ConceptSchema quantitativeHeuristicDescriptorSchema = new ConceptSchema(QUANTITATIVEHEURISTICDESCRIPTOR);
    add(quantitativeHeuristicDescriptorSchema, Class.forName("ontology.common.QuantitativeHeuristicDescriptor"));
    ConceptSchema msHeuristicDescriptorSchema = new ConceptSchema(MSHEURISTICDESCRIPTOR);
    add(msHeuristicDescriptorSchema, Class.forName("ontology.common.MSHeuristicDescriptor"));
    ConceptSchema ssHeuristicDescriptorSchema = new ConceptSchema(SSHEURISTICDESCRIPTOR);
    add(ssHeuristicDescriptorSchema, Class.forName("ontology.common.SSHeuristicDescriptor"));
    ConceptSchema descriptionSchema = new ConceptSchema(DESCRIPTION);
    add(descriptionSchema, Class.forName("ontology.common.Description"));
    ConceptSchema rvHeuristicDescriptorSchema = new ConceptSchema(RVHEURISTICDESCRIPTOR);
    add(rvHeuristicDescriptorSchema, Class.forName("ontology.common.RVHeuristicDescriptor"));
    ConceptSchema environmentalCategorySchema = new ConceptSchema(ENVIRONMENTALCATEGORY);
    add(environmentalCategorySchema, Class.forName("ontology.common.EnvironmentalCategory"));
    ConceptSchema structureSchema = new ConceptSchema(STRUCTURE);
    add(structureSchema, Class.forName("ontology.common.Structure"));
    ConceptSchema definedTermSchema = new ConceptSchema(DEFINEDTERM);
    add(definedTermSchema, Class.forName("ontology.common.DefinedTerm"));
    ConceptSchema singleValueSchema = new ConceptSchema(SINGLEVALUE);
    add(singleValueSchema, Class.forName("ontology.common.SingleValue"));
    ConceptSchema rangeValueSchema = new ConceptSchema(RANGEVALUE);
    add(rangeValueSchema, Class.forName("ontology.common.RangeValue"));
    ConceptSchema characterDescriptorSchema = new ConceptSchema(CHARACTERDESCRIPTOR);
    add(characterDescriptorSchema, Class.forName("ontology.common.CharacterDescriptor"));
    ConceptSchema svCharacterDescriptorSchema = new ConceptSchema(SVCHARACTERDESCRIPTOR);
    add(svCharacterDescriptorSchema, Class.forName("ontology.common.SVCharacterDescriptor"));
    ConceptSchema rvCharacterDescriptorSchema = new ConceptSchema(RVCHARACTERDESCRIPTOR);
    add(rvCharacterDescriptorSchema, Class.forName("ontology.common.RVCharacterDescriptor"));
    ConceptSchema heuristicDescriptorSchema = new ConceptSchema(HEURISTICDESCRIPTOR);
    add(heuristicDescriptorSchema, Class.forName("ontology.common.HeuristicDescriptor"));
    ConceptSchema qualitativeHeuristicDescriptorSchema = new ConceptSchema(QUALITATIVEHEURISTICDESCRIPTOR);
    add(qualitativeHeuristicDescriptorSchema, Class.forName("ontology.common.QualitativeHeuristicDescriptor"));
    ConceptSchema qualitativeCharacterDescriptorSchema = new ConceptSchema(QUALITATIVECHARACTERDESCRIPTOR);
    add(qualitativeCharacterDescriptorSchema, Class.forName("ontology.common.QualitativeCharacterDescriptor"));
    ConceptSchema ssCharacterDescriptorSchema = new ConceptSchema(SSCHARACTERDESCRIPTOR);
    add(ssCharacterDescriptorSchema, Class.forName("ontology.common.SSCharacterDescriptor"));
    ConceptSchema msCharacterDescriptorSchema = new ConceptSchema(MSCHARACTERDESCRIPTOR);
    add(msCharacterDescriptorSchema, Class.forName("ontology.common.MSCharacterDescriptor"));
    ConceptSchema quantitativeCharacterDescriptorSchema = new ConceptSchema(QUANTITATIVECHARACTERDESCRIPTOR);
    add(quantitativeCharacterDescriptorSchema, Class.forName("ontology.common.QuantitativeCharacterDescriptor"));
    ConceptSchema descriptorSchema = new ConceptSchema(DESCRIPTOR);
    add(descriptorSchema, Class.forName("ontology.common.Descriptor"));

    // adding AgentAction(s)

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema ownsSchema = new PredicateSchema(OWNS);
    add(ownsSchema, Class.forName("ontology.common.Owns"));
    PredicateSchema isDescriptiveElementSchema = new PredicateSchema(ISDESCRIPTIVEELEMENT);
    add(isDescriptiveElementSchema, Class.forName("ontology.common.IsDescriptiveElement"));
    PredicateSchema describesSchema = new PredicateSchema(DESCRIBES);
    add(describesSchema, Class.forName("ontology.common.Describes"));
    PredicateSchema describedBySchema = new PredicateSchema(DESCRIBEDBY);
    add(describedBySchema, Class.forName("ontology.common.DescribedBy"));
    PredicateSchema appliesToSchema = new PredicateSchema(APPLIESTO);
    add(appliesToSchema, Class.forName("ontology.common.AppliesTo"));


    // adding fields
    stateSchema.add(STATE_DESCRIBES, attributeSchema, 1, ObjectSchema.UNLIMITED);
    attributeSchema.add(ATTRIBUTE_APLIESTO, new ConceptSchema("Concept"), 1, ObjectSchema.UNLIMITED);
    attributeSchema.add(ATTRIBUTE_DESCRIBEDBY, new ConceptSchema("Concept"), 0, ObjectSchema.UNLIMITED);
    valueSchema.add(VALUE_MEASURINGUNIT, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    valueSchema.add(VALUE_DESCRIBES, attributeSchema, 1, ObjectSchema.UNLIMITED);
    descriptionSchema.add(DESCRIPTION_DESCRIPTORS, descriptorSchema, 1, ObjectSchema.UNLIMITED);
    environmentalCategorySchema.add(ENVIRONMENTALCATEGORY_OWNS, attributeSchema, 1, ObjectSchema.UNLIMITED);
    structureSchema.add(STRUCTURE_OWNS, attributeSchema, 1, ObjectSchema.UNLIMITED);
    definedTermSchema.add(DEFINEDTERM_DEFINITION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    definedTermSchema.add(DEFINEDTERM_TERM, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    singleValueSchema.add(SINGLEVALUE_VALUE, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    rangeValueSchema.add(RANGEVALUE_UPPERBOUND, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    rangeValueSchema.add(RANGEVALUE_LOWERBOUND, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    descriptorSchema.add(DESCRIPTOR_SCORE, new ConceptSchema("Concept"), 1, ObjectSchema.UNLIMITED);
    descriptorSchema.add(DESCRIPTOR_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    descriptorSchema.add(DESCRIPTOR_STRUCTURE, new ConceptSchema("Concept"), ObjectSchema.MANDATORY);
    ownsSchema.add(OWNS_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    ownsSchema.add(OWNS_DESCRIPTIVEELEMENT, new ConceptSchema("Concept"), ObjectSchema.MANDATORY);
    isDescriptiveElementSchema.add(ISDESCRIPTIVEELEMENT_DESCRIPTIVEELEMENT, new ConceptSchema("Concept"), ObjectSchema.MANDATORY);
    describesSchema.add(DESCRIBES_SCORE, new ConceptSchema("Concept"), 1, ObjectSchema.UNLIMITED);
    describesSchema.add(DESCRIBES_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    describedBySchema.add(DESCRIBEDBY_SCORE, new ConceptSchema("Concept"), 1, ObjectSchema.UNLIMITED);
    describedBySchema.add(DESCRIBEDBY_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    appliesToSchema.add(APPLIESTO_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    appliesToSchema.add(APPLIESTO_DESCRIPTIVEELEMENT, new ConceptSchema("Concept"), ObjectSchema.MANDATORY);

    // adding name mappings

    // adding inheritance
    stateSchema.addSuperSchema(definedTermSchema);
    attributeSchema.addSuperSchema(definedTermSchema);
    svHeuristicDescriptorSchema.addSuperSchema(quantitativeHeuristicDescriptorSchema);
    quantitativeHeuristicDescriptorSchema.addSuperSchema(heuristicDescriptorSchema);
    msHeuristicDescriptorSchema.addSuperSchema(qualitativeHeuristicDescriptorSchema);
    ssHeuristicDescriptorSchema.addSuperSchema(qualitativeHeuristicDescriptorSchema);
    rvHeuristicDescriptorSchema.addSuperSchema(quantitativeHeuristicDescriptorSchema);
    environmentalCategorySchema.addSuperSchema(definedTermSchema);
    structureSchema.addSuperSchema(definedTermSchema);
    singleValueSchema.addSuperSchema(valueSchema);
    rangeValueSchema.addSuperSchema(valueSchema);
    characterDescriptorSchema.addSuperSchema(descriptorSchema);
    svCharacterDescriptorSchema.addSuperSchema(quantitativeCharacterDescriptorSchema);
    rvCharacterDescriptorSchema.addSuperSchema(quantitativeCharacterDescriptorSchema);
    heuristicDescriptorSchema.addSuperSchema(descriptorSchema);
    qualitativeHeuristicDescriptorSchema.addSuperSchema(heuristicDescriptorSchema);
    qualitativeCharacterDescriptorSchema.addSuperSchema(characterDescriptorSchema);
    ssCharacterDescriptorSchema.addSuperSchema(qualitativeCharacterDescriptorSchema);
    msCharacterDescriptorSchema.addSuperSchema(qualitativeCharacterDescriptorSchema);
    quantitativeCharacterDescriptorSchema.addSuperSchema(characterDescriptorSchema);

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
