// file: TaxonomyOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.taxonomy;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: TaxonomyOntology.java
 * @author ontology bean generator
 * @version 2009/09/30, 13:34:31
 */
public class TaxonomyOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = -8627856865395943317L;

  //NAME
  public static final String ONTOLOGY_NAME = "Taxonomy";
  // The singleton instance of this ontology
  private static Ontology theInstance = new TaxonomyOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String ISSUCCESSORTAXONOF_OBJECTTAXON="objectTaxon";
    public static final String ISSUCCESSORTAXONOF_SUBJECTTAXON="subjectTaxon";
    public static final String ISSUCCESSORTAXONOF="IsSuccessorTaxonOf";
    public static final String ISPREDECESSORTAXONOF_OBJECTTAXON="objectTaxon";
    public static final String ISPREDECESSORTAXONOF_SUBJECTTAXON="subjectTaxon";
    public static final String ISPREDECESSORTAXONOF="IsPredecessorTaxonOf";
    public static final String DESCRIBES_ATTRIBUTE="attribute";
    public static final String DESCRIBES_SCORE="score";
    public static final String DESCRIBES="Describes";
    public static final String DESCRIBEDBY_ATTRIBUTE="attribute";
    public static final String DESCRIBEDBY_SCORE="score";
    public static final String DESCRIBEDBY="DescribedBy";
    public static final String APLIESTO_ATTRIBUTE="attribute";
    public static final String APLIESTO_DESCRIPTIVEELEMENT="descriptiveElement";
    public static final String APLIESTO="ApliesTo";
    public static final String OWNS_ATTRIBUTE="attribute";
    public static final String OWNS_DESCRIPTIVEELEMENT="descriptiveElement";
    public static final String OWNS="Owns";
    public static final String ISROOTTAXON_TAXON="taxon";
    public static final String ISROOTTAXON="IsRootTaxon";
    public static final String ISSHEETTAXON_TAXON="taxon";
    public static final String ISSHEETTAXON="IsSheetTaxon";
    public static final String STRUCTURE_OWNS="owns";
    public static final String STRUCTURE="Structure";
    public static final String ENVIRONMENTALCATEGORY_OWNS="owns";
    public static final String ENVIRONMENTALCATEGORY="EnvironmentalCategory";
    public static final String MODIFIER_SCOREWEIGHT="scoreWeight";
    public static final String MODIFIER_STRUCTUREWEIGHT="structureWeight";
    public static final String MODIFIER_ATTRIBUTEWEIGHT="attributeWeight";
    public static final String MODIFIER="Modifier";
    public static final String WEIGHTEDDESCRIPTION_WEIGHTEDDESCRIPTORS="weightedDescriptors";
    public static final String WEIGHTEDDESCRIPTION="WeightedDescription";
    public static final String WEIGHTEDDESCRIPTOR_MODIFIER="modifier";
    public static final String WEIGHTEDDESCRIPTOR_DESCRIPTOR="descriptor";
    public static final String WEIGHTEDDESCRIPTOR="WeightedDescriptor";
    public static final String STATE_DESCRIBES="describes";
    public static final String STATE="State";
    public static final String VALUE_DESCRIBES="describes";
    public static final String VALUE_MEASURINGUNIT="measuringUnit";
    public static final String VALUE="Value";
    public static final String TAXON_NAME="name";
    public static final String TAXON_WEIGHTEDDESCRIPTION="weightedDescription";
    public static final String TAXON_LEVEL="level";
    public static final String TAXON_PREDECESSOR="predecessor";
    public static final String TAXON_SUCCESSORS="successors";
    public static final String TAXON="Taxon";
    public static final String DESCRIPTION_DESCRIPTORS="descriptors";
    public static final String DESCRIPTION="Description";
    public static final String RVHEURISTICDESCRIPTOR="RVHeuristicDescriptor";
    public static final String SVHEURISTICDESCRIPTOR="SVHeuristicDescriptor";
    public static final String ATTRIBUTE_DESCRIBEDBY="describedBy";
    public static final String ATTRIBUTE_APLIESTO="apliesTo";
    public static final String ATTRIBUTE="Attribute";
    public static final String HEURISTICDESCRIPTOR="HeuristicDescriptor";
    public static final String RVCHARACTERDESCRIPTOR="RVCharacterDescriptor";
    public static final String SVCHARACTERDESCRIPTOR="SVCharacterDescriptor";
    public static final String QUANTITATIVECHARACTERDESCRIPTOR="QuantitativeCharacterDescriptor";
    public static final String QUANTITATIVEHEURISTICDESCRIPTOR="QuantitativeHeuristicDescriptor";
    public static final String MSHEURISTICDESCRIPTOR="MSHeuristicDescriptor";
    public static final String SSHEURISTICDESCRIPTOR="SSHeuristicDescriptor";
    public static final String QUALITATIVEHEURISTICDESCRIPTOR="QualitativeHeuristicDescriptor";
    public static final String SINGLEVALUE_VALUE="value";
    public static final String SINGLEVALUE="SingleValue";
    public static final String RANGEVALUE_LOWERBOUND="lowerBound";
    public static final String RANGEVALUE_UPPERBOUND="upperBound";
    public static final String RANGEVALUE="RangeValue";
    public static final String DEFINEDTERM_TERM="term";
    public static final String DEFINEDTERM_DEFINITION="definition";
    public static final String DEFINEDTERM="DefinedTerm";
    public static final String SSCHARACTERDESCRIPTOR="SSCharacterDescriptor";
    public static final String MSCHARACTERDESCRIPTOR="MSCharacterDescriptor";
    public static final String CHARACTERDESCRIPTOR="CharacterDescriptor";
    public static final String QUALITATIVECHARACTERDESCRIPTOR="QualitativeCharacterDescriptor";
    public static final String DESCRIPTOR_STRUCTURE="structure";
    public static final String DESCRIPTOR_ATTRIBUTE="attribute";
    public static final String DESCRIPTOR_SCORE="score";
    public static final String DESCRIPTOR="Descriptor";

  /**
   * Constructor
  */
  private TaxonomyOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema descriptorSchema = new ConceptSchema(DESCRIPTOR);
    add(descriptorSchema, ontology.taxonomy.Descriptor.class);
    ConceptSchema qualitativeCharacterDescriptorSchema = new ConceptSchema(QUALITATIVECHARACTERDESCRIPTOR);
    add(qualitativeCharacterDescriptorSchema, ontology.taxonomy.QualitativeCharacterDescriptor.class);
    ConceptSchema characterDescriptorSchema = new ConceptSchema(CHARACTERDESCRIPTOR);
    add(characterDescriptorSchema, ontology.taxonomy.CharacterDescriptor.class);
    ConceptSchema msCharacterDescriptorSchema = new ConceptSchema(MSCHARACTERDESCRIPTOR);
    add(msCharacterDescriptorSchema, ontology.taxonomy.MSCharacterDescriptor.class);
    ConceptSchema ssCharacterDescriptorSchema = new ConceptSchema(SSCHARACTERDESCRIPTOR);
    add(ssCharacterDescriptorSchema, ontology.taxonomy.SSCharacterDescriptor.class);
    ConceptSchema definedTermSchema = new ConceptSchema(DEFINEDTERM);
    add(definedTermSchema, ontology.taxonomy.DefinedTerm.class);
    ConceptSchema rangeValueSchema = new ConceptSchema(RANGEVALUE);
    add(rangeValueSchema, ontology.taxonomy.RangeValue.class);
    ConceptSchema singleValueSchema = new ConceptSchema(SINGLEVALUE);
    add(singleValueSchema, ontology.taxonomy.SingleValue.class);
    ConceptSchema qualitativeHeuristicDescriptorSchema = new ConceptSchema(QUALITATIVEHEURISTICDESCRIPTOR);
    add(qualitativeHeuristicDescriptorSchema, ontology.taxonomy.QualitativeHeuristicDescriptor.class);
    ConceptSchema ssHeuristicDescriptorSchema = new ConceptSchema(SSHEURISTICDESCRIPTOR);
    add(ssHeuristicDescriptorSchema, ontology.taxonomy.SSHeuristicDescriptor.class);
    ConceptSchema msHeuristicDescriptorSchema = new ConceptSchema(MSHEURISTICDESCRIPTOR);
    add(msHeuristicDescriptorSchema, ontology.taxonomy.MSHeuristicDescriptor.class);
    ConceptSchema quantitativeHeuristicDescriptorSchema = new ConceptSchema(QUANTITATIVEHEURISTICDESCRIPTOR);
    add(quantitativeHeuristicDescriptorSchema, ontology.taxonomy.QuantitativeHeuristicDescriptor.class);
    ConceptSchema quantitativeCharacterDescriptorSchema = new ConceptSchema(QUANTITATIVECHARACTERDESCRIPTOR);
    add(quantitativeCharacterDescriptorSchema, ontology.taxonomy.QuantitativeCharacterDescriptor.class);
    ConceptSchema svCharacterDescriptorSchema = new ConceptSchema(SVCHARACTERDESCRIPTOR);
    add(svCharacterDescriptorSchema, ontology.taxonomy.SVCharacterDescriptor.class);
    ConceptSchema rvCharacterDescriptorSchema = new ConceptSchema(RVCHARACTERDESCRIPTOR);
    add(rvCharacterDescriptorSchema, ontology.taxonomy.RVCharacterDescriptor.class);
    ConceptSchema heuristicDescriptorSchema = new ConceptSchema(HEURISTICDESCRIPTOR);
    add(heuristicDescriptorSchema, ontology.taxonomy.HeuristicDescriptor.class);
    ConceptSchema attributeSchema = new ConceptSchema(ATTRIBUTE);
    add(attributeSchema, ontology.taxonomy.Attribute.class);
    ConceptSchema svHeuristicDescriptorSchema = new ConceptSchema(SVHEURISTICDESCRIPTOR);
    add(svHeuristicDescriptorSchema, ontology.taxonomy.SVHeuristicDescriptor.class);
    ConceptSchema rvHeuristicDescriptorSchema = new ConceptSchema(RVHEURISTICDESCRIPTOR);
    add(rvHeuristicDescriptorSchema, ontology.taxonomy.RVHeuristicDescriptor.class);
    ConceptSchema descriptionSchema = new ConceptSchema(DESCRIPTION);
    add(descriptionSchema, ontology.taxonomy.Description.class);
    ConceptSchema taxonSchema = new ConceptSchema(TAXON);
    add(taxonSchema, ontology.taxonomy.Taxon.class);
    ConceptSchema valueSchema = new ConceptSchema(VALUE);
    add(valueSchema, ontology.taxonomy.Value.class);
    ConceptSchema stateSchema = new ConceptSchema(STATE);
    add(stateSchema, ontology.taxonomy.State.class);
    ConceptSchema weightedDescriptorSchema = new ConceptSchema(WEIGHTEDDESCRIPTOR);
    add(weightedDescriptorSchema, ontology.taxonomy.WeightedDescriptor.class);
    ConceptSchema weightedDescriptionSchema = new ConceptSchema(WEIGHTEDDESCRIPTION);
    add(weightedDescriptionSchema, ontology.taxonomy.WeightedDescription.class);
    ConceptSchema modifierSchema = new ConceptSchema(MODIFIER);
    add(modifierSchema, ontology.taxonomy.Modifier.class);
    ConceptSchema environmentalCategorySchema = new ConceptSchema(ENVIRONMENTALCATEGORY);
    add(environmentalCategorySchema, ontology.taxonomy.EnvironmentalCategory.class);
    ConceptSchema structureSchema = new ConceptSchema(STRUCTURE);
    add(structureSchema, ontology.taxonomy.Structure.class);

    // adding AgentAction(s)

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema isSheetTaxonSchema = new PredicateSchema(ISSHEETTAXON);
    add(isSheetTaxonSchema, ontology.taxonomy.IsSheetTaxon.class);
    PredicateSchema isRootTaxonSchema = new PredicateSchema(ISROOTTAXON);
    add(isRootTaxonSchema, ontology.taxonomy.IsRootTaxon.class);
    PredicateSchema ownsSchema = new PredicateSchema(OWNS);
    add(ownsSchema, ontology.taxonomy.Owns.class);
    PredicateSchema apliesToSchema = new PredicateSchema(APLIESTO);
    add(apliesToSchema, ontology.taxonomy.ApliesTo.class);
    PredicateSchema describedBySchema = new PredicateSchema(DESCRIBEDBY);
    add(describedBySchema, ontology.taxonomy.DescribedBy.class);
    PredicateSchema describesSchema = new PredicateSchema(DESCRIBES);
    add(describesSchema, ontology.taxonomy.Describes.class);
    PredicateSchema isPredecessorTaxonOfSchema = new PredicateSchema(ISPREDECESSORTAXONOF);
    add(isPredecessorTaxonOfSchema, ontology.taxonomy.IsPredecessorTaxonOf.class);
    PredicateSchema isSuccessorTaxonOfSchema = new PredicateSchema(ISSUCCESSORTAXONOF);
    add(isSuccessorTaxonOfSchema, ontology.taxonomy.IsSuccessorTaxonOf.class);


    // adding fields
    descriptorSchema.add(DESCRIPTOR_SCORE, new ConceptSchema("Concept"), 1, ObjectSchema.UNLIMITED);
    descriptorSchema.add(DESCRIPTOR_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    descriptorSchema.add(DESCRIPTOR_STRUCTURE, new ConceptSchema("Concept"), ObjectSchema.MANDATORY);
    definedTermSchema.add(DEFINEDTERM_DEFINITION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    definedTermSchema.add(DEFINEDTERM_TERM, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    rangeValueSchema.add(RANGEVALUE_UPPERBOUND, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    rangeValueSchema.add(RANGEVALUE_LOWERBOUND, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    singleValueSchema.add(SINGLEVALUE_VALUE, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    attributeSchema.add(ATTRIBUTE_APLIESTO, new ConceptSchema("Concept"), 1, ObjectSchema.UNLIMITED);
    attributeSchema.add(ATTRIBUTE_DESCRIBEDBY, new ConceptSchema("Concept"), 0, ObjectSchema.UNLIMITED);
    descriptionSchema.add(DESCRIPTION_DESCRIPTORS, descriptorSchema, 1, ObjectSchema.UNLIMITED);
    taxonSchema.add(TAXON_SUCCESSORS, taxonSchema, 0, ObjectSchema.UNLIMITED);
    taxonSchema.add(TAXON_PREDECESSOR, taxonSchema, ObjectSchema.OPTIONAL);
    taxonSchema.add(TAXON_LEVEL, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    taxonSchema.add(TAXON_WEIGHTEDDESCRIPTION, weightedDescriptionSchema, ObjectSchema.MANDATORY);
    taxonSchema.add(TAXON_NAME, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    valueSchema.add(VALUE_MEASURINGUNIT, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    valueSchema.add(VALUE_DESCRIBES, attributeSchema, 1, ObjectSchema.UNLIMITED);
    stateSchema.add(STATE_DESCRIBES, attributeSchema, 1, ObjectSchema.UNLIMITED);
    weightedDescriptorSchema.add(WEIGHTEDDESCRIPTOR_DESCRIPTOR, descriptorSchema, ObjectSchema.MANDATORY);
    weightedDescriptorSchema.add(WEIGHTEDDESCRIPTOR_MODIFIER, modifierSchema, ObjectSchema.MANDATORY);
    weightedDescriptionSchema.add(WEIGHTEDDESCRIPTION_WEIGHTEDDESCRIPTORS, weightedDescriptorSchema, 1, ObjectSchema.UNLIMITED);
    modifierSchema.add(MODIFIER_ATTRIBUTEWEIGHT, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    modifierSchema.add(MODIFIER_STRUCTUREWEIGHT, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    modifierSchema.add(MODIFIER_SCOREWEIGHT, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    environmentalCategorySchema.add(ENVIRONMENTALCATEGORY_OWNS, attributeSchema, 1, ObjectSchema.UNLIMITED);
    structureSchema.add(STRUCTURE_OWNS, attributeSchema, 1, ObjectSchema.UNLIMITED);
    isSheetTaxonSchema.add(ISSHEETTAXON_TAXON, taxonSchema, ObjectSchema.MANDATORY);
    isRootTaxonSchema.add(ISROOTTAXON_TAXON, taxonSchema, ObjectSchema.MANDATORY);
    ownsSchema.add(OWNS_DESCRIPTIVEELEMENT, new ConceptSchema("Concept"), ObjectSchema.OPTIONAL);
    ownsSchema.add(OWNS_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    apliesToSchema.add(APLIESTO_DESCRIPTIVEELEMENT, new ConceptSchema("Concept"), ObjectSchema.OPTIONAL);
    apliesToSchema.add(APLIESTO_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    describedBySchema.add(DESCRIBEDBY_SCORE, new ConceptSchema("Concept"), 1, ObjectSchema.UNLIMITED);
    describedBySchema.add(DESCRIBEDBY_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    describesSchema.add(DESCRIBES_SCORE, new ConceptSchema("Concept"), 1, ObjectSchema.UNLIMITED);
    describesSchema.add(DESCRIBES_ATTRIBUTE, attributeSchema, ObjectSchema.MANDATORY);
    isPredecessorTaxonOfSchema.add(ISPREDECESSORTAXONOF_SUBJECTTAXON, taxonSchema, ObjectSchema.MANDATORY);
    isPredecessorTaxonOfSchema.add(ISPREDECESSORTAXONOF_OBJECTTAXON, taxonSchema, ObjectSchema.MANDATORY);
    isSuccessorTaxonOfSchema.add(ISSUCCESSORTAXONOF_SUBJECTTAXON, taxonSchema, ObjectSchema.MANDATORY);
    isSuccessorTaxonOfSchema.add(ISSUCCESSORTAXONOF_OBJECTTAXON, taxonSchema, ObjectSchema.MANDATORY);

    // adding name mappings

    // adding inheritance
    qualitativeCharacterDescriptorSchema.addSuperSchema(characterDescriptorSchema);
    characterDescriptorSchema.addSuperSchema(descriptorSchema);
    msCharacterDescriptorSchema.addSuperSchema(qualitativeCharacterDescriptorSchema);
    ssCharacterDescriptorSchema.addSuperSchema(qualitativeCharacterDescriptorSchema);
    rangeValueSchema.addSuperSchema(valueSchema);
    singleValueSchema.addSuperSchema(valueSchema);
    qualitativeHeuristicDescriptorSchema.addSuperSchema(heuristicDescriptorSchema);
    ssHeuristicDescriptorSchema.addSuperSchema(qualitativeHeuristicDescriptorSchema);
    msHeuristicDescriptorSchema.addSuperSchema(qualitativeHeuristicDescriptorSchema);
    quantitativeHeuristicDescriptorSchema.addSuperSchema(heuristicDescriptorSchema);
    quantitativeCharacterDescriptorSchema.addSuperSchema(characterDescriptorSchema);
    svCharacterDescriptorSchema.addSuperSchema(quantitativeCharacterDescriptorSchema);
    rvCharacterDescriptorSchema.addSuperSchema(quantitativeCharacterDescriptorSchema);
    heuristicDescriptorSchema.addSuperSchema(descriptorSchema);
    attributeSchema.addSuperSchema(definedTermSchema);
    svHeuristicDescriptorSchema.addSuperSchema(quantitativeHeuristicDescriptorSchema);
    rvHeuristicDescriptorSchema.addSuperSchema(quantitativeHeuristicDescriptorSchema);
    stateSchema.addSuperSchema(definedTermSchema);
    environmentalCategorySchema.addSuperSchema(definedTermSchema);
    structureSchema.addSuperSchema(definedTermSchema);

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
