// file: TaxonomyKbBeanFactory.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.taxonomy;

import ontology.taxonomy.impl.*;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import jade.util.leap.ArrayList;

import edu.stanford.smi.protege.model.KnowledgeBase;
import edu.stanford.smi.protege.model.Instance;
import edu.stanford.smi.protege.model.Slot;
import edu.stanford.smi.protegex.owl.model.OWLModel;

/** file: TaxonomyKbBeanFactory.java
 * @author ontology bean generator
 * @version 2009/09/30, 13:34:31
 */
public class TaxonomyKbBeanFactory {
  private static final long serialVersionUID = -8627856865395943317L;

  private KnowledgeBase kb = null;
  private OWLModel owlModel = null;
  private java.util.HashMap<String, Object> beanInstances = null;
  public static java.util.HashMap<String, String> typeToMethodName = new java.util.HashMap<String, String> ();

  private Object tempAnyValue;
  private Boolean tempBooleanValue;
  private Class tempClsValue;
  private Float tempFloatValue;
  private Instance tempInstanceValue;
  private Integer tempIntegerValue;
  private String tempStringValue;
  private String tempSymbolValue;

  private java.util.ArrayList  tempAnyValues;
  private java.util.ArrayList <Boolean> tempBooleanValues;
  private java.util.ArrayList <Class> tempClsValues;
  private java.util.ArrayList <Float> tempFloatValues;
  private java.util.ArrayList <Instance> tempInstanceValues;
  private java.util.ArrayList <Integer> tempIntegerValues;
  private java.util.ArrayList <String> tempStringValues;
  private java.util.ArrayList <String> tempSymbolValues;


  //Constructor(s)
  public TaxonomyKbBeanFactory(KnowledgeBase kb) {
    this.kb = kb;
    if (kb instanceof OWLModel)
      this.owlModel = (OWLModel) kb;
    else
      this.owlModel = null;
    beanInstances = new java.util.HashMap<String, Object>();
  }

  /**
   * Protege name: Descriptor
  */
  public Descriptor getDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Descriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Descriptor javaInst = new DefaultDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: QualitativeCharacterDescriptor
  */
  public QualitativeCharacterDescriptor getQualitativeCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (QualitativeCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    QualitativeCharacterDescriptor javaInst = new DefaultQualitativeCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: CharacterDescriptor
  */
  public CharacterDescriptor getCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (CharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    CharacterDescriptor javaInst = new DefaultCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: MSCharacterDescriptor
  */
  public MSCharacterDescriptor getMSCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (MSCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    MSCharacterDescriptor javaInst = new DefaultMSCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: SSCharacterDescriptor
  */
  public SSCharacterDescriptor getSSCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SSCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SSCharacterDescriptor javaInst = new DefaultSSCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Define the terms utilized in the taxonomic  hierarchy
   * Protege name: DefinedTerm
  */
  public DefinedTerm getDefinedTerm(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (DefinedTerm)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    DefinedTerm javaInst = new DefaultDefinedTerm(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempStringValue = getStringValue( protegeInst, kb.getSlot( "definition" ) );
    if (tempStringValue != null) {
      javaInst.setDefinition(tempStringValue);
    }

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst.setTerm(tempStringValue);
    }

    return javaInst;
  }

  /**
   * Protege name: RangeValue
  */
  public RangeValue getRangeValue(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (RangeValue)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    RangeValue javaInst = new DefaultRangeValue(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempSymbolValue = getStringValue( protegeInst, kb.getSlot( "measuringUnit" ) );
    if (tempSymbolValue != null) {
      javaInst.setMeasuringUnit(tempSymbolValue);
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "upperBound" ) );
    if (tempFloatValue != null) {
      javaInst.setUpperBound(tempFloatValue);
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "describes" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addDescribes( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"describes\" in instance " + instanceName);
        }
      }
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "lowerBound" ) );
    if (tempFloatValue != null) {
      javaInst.setLowerBound(tempFloatValue);
    }

    return javaInst;
  }

  /**
   * Protege name: SingleValue
  */
  public SingleValue getSingleValue(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SingleValue)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SingleValue javaInst = new DefaultSingleValue(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempSymbolValue = getStringValue( protegeInst, kb.getSlot( "measuringUnit" ) );
    if (tempSymbolValue != null) {
      javaInst.setMeasuringUnit(tempSymbolValue);
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "value" ) );
    if (tempFloatValue != null) {
      javaInst.setValue(tempFloatValue);
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "describes" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addDescribes( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"describes\" in instance " + instanceName);
        }
      }
    }

    return javaInst;
  }

  /**
   * Protege name: QualitativeHeuristicDescriptor
  */
  public QualitativeHeuristicDescriptor getQualitativeHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (QualitativeHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    QualitativeHeuristicDescriptor javaInst = new DefaultQualitativeHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: SSHeuristicDescriptor
  */
  public SSHeuristicDescriptor getSSHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SSHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SSHeuristicDescriptor javaInst = new DefaultSSHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: MSHeuristicDescriptor
  */
  public MSHeuristicDescriptor getMSHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (MSHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    MSHeuristicDescriptor javaInst = new DefaultMSHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: QuantitativeHeuristicDescriptor
  */
  public QuantitativeHeuristicDescriptor getQuantitativeHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (QuantitativeHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    QuantitativeHeuristicDescriptor javaInst = new DefaultQuantitativeHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: QuantitativeCharacterDescriptor
  */
  public QuantitativeCharacterDescriptor getQuantitativeCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (QuantitativeCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    QuantitativeCharacterDescriptor javaInst = new DefaultQuantitativeCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: SVCharacterDescriptor
  */
  public SVCharacterDescriptor getSVCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SVCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SVCharacterDescriptor javaInst = new DefaultSVCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: RVCharacterDescriptor
  */
  public RVCharacterDescriptor getRVCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (RVCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    RVCharacterDescriptor javaInst = new DefaultRVCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: HeuristicDescriptor
  */
  public HeuristicDescriptor getHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (HeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    HeuristicDescriptor javaInst = new DefaultHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * It's a subclass of a defined term
   * Protege name: Attribute
  */
  public Attribute getAttribute(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Attribute)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Attribute javaInst = new DefaultAttribute(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempStringValue = getStringValue( protegeInst, kb.getSlot( "definition" ) );
    if (tempStringValue != null) {
      javaInst.setDefinition(tempStringValue);
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "apliesTo" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addApliesTo( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "describedBy" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addDescribedBy( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst.setTerm(tempStringValue);
    }

    return javaInst;
  }

  /**
   * Protege name: SVHeuristicDescriptor
  */
  public SVHeuristicDescriptor getSVHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SVHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SVHeuristicDescriptor javaInst = new DefaultSVHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: RVHeuristicDescriptor
  */
  public RVHeuristicDescriptor getRVHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (RVHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    RVHeuristicDescriptor javaInst = new DefaultRVHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    return javaInst;
  }

  /**
   * Protege name: Description
  */
  public Description getDescription(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Description)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Description javaInst = new DefaultDescription(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "descriptors" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Descriptor") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addDescriptors( (Descriptor) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"descriptors\" in instance " + instanceName);
        }
      }
    }

    return javaInst;
  }

  /**
   * Protege name: Taxon
  */
  public Taxon getTaxon(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Taxon)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Taxon javaInst = new DefaultTaxon(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "successors" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addSuccessors( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"successors\" in instance " + instanceName);
        }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "predecessor" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setPredecessor( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"predecessor\" in instance " + instanceName);
        }
    }

    tempSymbolValue = getStringValue( protegeInst, kb.getSlot( "level" ) );
    if (tempSymbolValue != null) {
      javaInst.setLevel(tempSymbolValue);
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "weightedDescription" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("WeightedDescription") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setWeightedDescription( (WeightedDescription) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"weightedDescription\" in instance " + instanceName);
        }
    }

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "name" ) );
    if (tempStringValue != null) {
      javaInst.setName(tempStringValue);
    }

    return javaInst;
  }

  /**
   * Protege name: Value
  */
  public Value getValue(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Value)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Value javaInst = new DefaultValue(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempSymbolValue = getStringValue( protegeInst, kb.getSlot( "measuringUnit" ) );
    if (tempSymbolValue != null) {
      javaInst.setMeasuringUnit(tempSymbolValue);
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "describes" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addDescribes( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"describes\" in instance " + instanceName);
        }
      }
    }

    return javaInst;
  }

  /**
   * It's a subclass of a defined term
   * Protege name: State
  */
  public State getState(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (State)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    State javaInst = new DefaultState(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempStringValue = getStringValue( protegeInst, kb.getSlot( "definition" ) );
    if (tempStringValue != null) {
      javaInst.setDefinition(tempStringValue);
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "describes" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addDescribes( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"describes\" in instance " + instanceName);
        }
      }
    }

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst.setTerm(tempStringValue);
    }

    return javaInst;
  }

  /**
   * Protege name: WeightedDescriptor
  */
  public WeightedDescriptor getWeightedDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (WeightedDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    WeightedDescriptor javaInst = new DefaultWeightedDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "descriptor" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Descriptor") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setDescriptor( (Descriptor) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"descriptor\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "modifier" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Modifier") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setModifier( (Modifier) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"modifier\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: WeightedDescription
  */
  public WeightedDescription getWeightedDescription(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (WeightedDescription)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    WeightedDescription javaInst = new DefaultWeightedDescription(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "weightedDescriptors" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("WeightedDescriptor") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addWeightedDescriptors( (WeightedDescriptor) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"weightedDescriptors\" in instance " + instanceName);
        }
      }
    }

    return javaInst;
  }

  /**
   * Protege name: Modifier
  */
  public Modifier getModifier(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Modifier)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Modifier javaInst = new DefaultModifier(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "attributeWeight" ) );
    if (tempFloatValue != null) {
      javaInst.setAttributeWeight(tempFloatValue);
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "structureWeight" ) );
    if (tempFloatValue != null) {
      javaInst.setStructureWeight(tempFloatValue);
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "scoreWeight" ) );
    if (tempFloatValue != null) {
      javaInst.setScoreWeight(tempFloatValue);
    }

    return javaInst;
  }

  /**
   * Protege name: EnvironmentalCategory
  */
  public EnvironmentalCategory getEnvironmentalCategory(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (EnvironmentalCategory)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    EnvironmentalCategory javaInst = new DefaultEnvironmentalCategory(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempStringValue = getStringValue( protegeInst, kb.getSlot( "definition" ) );
    if (tempStringValue != null) {
      javaInst.setDefinition(tempStringValue);
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "owns" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addOwns( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"owns\" in instance " + instanceName);
        }
      }
    }

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst.setTerm(tempStringValue);
    }

    return javaInst;
  }

  /**
   * It's a subclass of a defined term
   * Protege name: Structure
  */
  public Structure getStructure(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Structure)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Structure javaInst = new DefaultStructure(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempStringValue = getStringValue( protegeInst, kb.getSlot( "definition" ) );
    if (tempStringValue != null) {
      javaInst.setDefinition(tempStringValue);
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "owns" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addOwns( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"owns\" in instance " + instanceName);
        }
      }
    }

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst.setTerm(tempStringValue);
    }

    return javaInst;
  }

  /**
   * Protege name: IsSheetTaxon
  */
  public IsSheetTaxon getIsSheetTaxon(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (IsSheetTaxon)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    IsSheetTaxon javaInst = new DefaultIsSheetTaxon(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "taxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"taxon\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: IsRootTaxon
  */
  public IsRootTaxon getIsRootTaxon(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (IsRootTaxon)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    IsRootTaxon javaInst = new DefaultIsRootTaxon(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "taxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"taxon\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: Owns
  */
  public Owns getOwns(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Owns)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Owns javaInst = new DefaultOwns(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "descriptiveElement" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setDescriptiveElement( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: ApliesTo
  */
  public ApliesTo getApliesTo(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (ApliesTo)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    ApliesTo javaInst = new DefaultApliesTo(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "descriptiveElement" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setDescriptiveElement( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: DescribedBy
  */
  public DescribedBy getDescribedBy(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (DescribedBy)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    DescribedBy javaInst = new DefaultDescribedBy(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: Describes
  */
  public Describes getDescribes(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Describes)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Describes javaInst = new DefaultDescribes(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (Object) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (Attribute) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: IsPredecessorTaxonOf
  */
  public IsPredecessorTaxonOf getIsPredecessorTaxonOf(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (IsPredecessorTaxonOf)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    IsPredecessorTaxonOf javaInst = new DefaultIsPredecessorTaxonOf(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "subjectTaxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setSubjectTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"subjectTaxon\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "objectTaxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setObjectTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"objectTaxon\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: IsSuccessorTaxonOf
  */
  public IsSuccessorTaxonOf getIsSuccessorTaxonOf(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (IsSuccessorTaxonOf)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    IsSuccessorTaxonOf javaInst = new DefaultIsSuccessorTaxonOf(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "subjectTaxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setSubjectTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"subjectTaxon\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "objectTaxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setObjectTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"objectTaxon\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  //Typed access methods to slot values
  private static Instance getInstanceValue(Instance theInst, Slot theSlot) {
    return (Instance)theInst.getOwnSlotValue(theSlot);
  }

  private static java.util.ArrayList<Instance> getInstanceValues(Instance theInst, Slot theSlot) {
    return new java.util.ArrayList<Instance>(theInst.getOwnSlotValues(theSlot));
  }

  private static Float getFloatValue(Instance theInst, Slot theSlot) {
    return (Float)theInst.getOwnSlotValue(theSlot);
  }

  private static String getStringValue(Instance theInst, Slot theSlot) {
    return (String)theInst.getOwnSlotValue(theSlot);
  }

  private static String getStringValue(Instance theInst, Slot theSlot) {
    return (String)theInst.getOwnSlotValue(theSlot);
  }


  public Object getJadeInstanceFor(Instance tempInstanceValue) throws TaxonomyKbBeanFactoryException {
    //TODO test for multiple types
    String methodName = typeToMethodName.get(tempInstanceValue.getDirectType().getName());
    if (methodName != null) {
      try {
        Method method = this.getClass().getMethod(methodName, new Class[] {Class.forName("java.lang.String")});
        return method.invoke(this, new Object[] {tempInstanceValue.getName()});
      }
      catch (SecurityException e) {
         throw new TaxonomyKbBeanFactoryException(e);
      } catch (NoSuchMethodException e) {
         throw new TaxonomyKbBeanFactoryException(e);
      } catch (ClassNotFoundException e) {
         throw new TaxonomyKbBeanFactoryException(e);
      }
      catch (IllegalArgumentException e) {
         throw new TaxonomyKbBeanFactoryException("Exception while invoking method " + methodName + " for instance " + tempInstanceValue.getName(), e);
      } catch (IllegalAccessException e) {
         throw new TaxonomyKbBeanFactoryException("Exception while invoking method " + methodName + " for instance " + tempInstanceValue.getName(), e);
      } catch (InvocationTargetException e) {
         throw new TaxonomyKbBeanFactoryException("Exception while invoking method " + methodName + " for instance " + tempInstanceValue.getName(), e);
      }
    }
    return null;
  }

  static {
    typeToMethodName.put("Descriptor", "getDescriptor");
    typeToMethodName.put("QualitativeCharacterDescriptor", "getQualitativeCharacterDescriptor");
    typeToMethodName.put("CharacterDescriptor", "getCharacterDescriptor");
    typeToMethodName.put("MSCharacterDescriptor", "getMSCharacterDescriptor");
    typeToMethodName.put("SSCharacterDescriptor", "getSSCharacterDescriptor");
    typeToMethodName.put("DefinedTerm", "getDefinedTerm");
    typeToMethodName.put("RangeValue", "getRangeValue");
    typeToMethodName.put("SingleValue", "getSingleValue");
    typeToMethodName.put("QualitativeHeuristicDescriptor", "getQualitativeHeuristicDescriptor");
    typeToMethodName.put("SSHeuristicDescriptor", "getSSHeuristicDescriptor");
    typeToMethodName.put("MSHeuristicDescriptor", "getMSHeuristicDescriptor");
    typeToMethodName.put("QuantitativeHeuristicDescriptor", "getQuantitativeHeuristicDescriptor");
    typeToMethodName.put("QuantitativeCharacterDescriptor", "getQuantitativeCharacterDescriptor");
    typeToMethodName.put("SVCharacterDescriptor", "getSVCharacterDescriptor");
    typeToMethodName.put("RVCharacterDescriptor", "getRVCharacterDescriptor");
    typeToMethodName.put("HeuristicDescriptor", "getHeuristicDescriptor");
    typeToMethodName.put("Attribute", "getAttribute");
    typeToMethodName.put("SVHeuristicDescriptor", "getSVHeuristicDescriptor");
    typeToMethodName.put("RVHeuristicDescriptor", "getRVHeuristicDescriptor");
    typeToMethodName.put("Description", "getDescription");
    typeToMethodName.put("Taxon", "getTaxon");
    typeToMethodName.put("Value", "getValue");
    typeToMethodName.put("State", "getState");
    typeToMethodName.put("WeightedDescriptor", "getWeightedDescriptor");
    typeToMethodName.put("WeightedDescription", "getWeightedDescription");
    typeToMethodName.put("Modifier", "getModifier");
    typeToMethodName.put("EnvironmentalCategory", "getEnvironmentalCategory");
    typeToMethodName.put("Structure", "getStructure");
    typeToMethodName.put("IsSheetTaxon", "getIsSheetTaxon");
    typeToMethodName.put("IsRootTaxon", "getIsRootTaxon");
    typeToMethodName.put("Owns", "getOwns");
    typeToMethodName.put("ApliesTo", "getApliesTo");
    typeToMethodName.put("DescribedBy", "getDescribedBy");
    typeToMethodName.put("Describes", "getDescribes");
    typeToMethodName.put("IsPredecessorTaxonOf", "getIsPredecessorTaxonOf");
    typeToMethodName.put("IsSuccessorTaxonOf", "getIsSuccessorTaxonOf");
  }

}
